Repository alvin-test-org/cherry-pick-test, pull requests merged in 2020-03, with the labels that each got.

#3 test doc label
  doc.txt
Labels: docs

#5 test doc label again with jq
  doc.txt
Labels: docs

#8 remember to add label...
  doc.txt
Labels: docs

#9 without merge conflict
  doc.txt
Labels: docs

#12 try github api again
  doc.txt
Labels: docs

#13 test doc
  doc.txt
Labels: docs

#14 test again
  doc.txt
Labels: docs

#15 test again again
  doc.txt
Labels: docs

#4 Test multiple commits
  multiple.txt
Labels: docs

#1 test backport label
  backport.txt
Labels: backport/1.7

#2 test 2 labels
  2labels.txt
Labels: backport/1.6, backport/1.7

#16 Update backport.txt
  backport.txt
Labels: backport/1.7

#17 Update doc.txt
  doc.txt
Labels: docs

#18 Update doc.txt
  doc.txt
Labels: docs
